server:
  port: 8090

spring:
  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:oracle:thin:@43.200.33.166:1522/xe #나중에 할거구
    #url: jdbc:oracle:thin:@192.168.0.24:1522/xe #오라클 도커만들어서 해놓은거임
#    url: jdbc:oracle:thin:@localhost:1521/xe #로컬
    url: jdbc:mysql://localhost:3306/choonsik?serverTimezone=UTC&characterEncoding=UTF-8 #로컬
    username: choonsik
    password: choonsik
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/productimgs/

# 이미지 저장할 위치와 응답할 때 이미지 주소 세팅
image:
  # WebConfig에 세팅
  #add-resource-locations: classpath:/static/productimgs/ #여기서 불러다가 쓸거임?
  #add-resource-handler: /productimgs/**

  add-resource-locations: /productimgs/
  add-resource-handler: /productimgs/**


  # ProductService에 세팅
  #image-dir: src/main/resources/static/productimgs/
  image-dir: /productimgs/
  #image-url: http://43.200.33.166:8090/productimgs/
  #image-url: http://192.168.0.24:8090/productimgs/
  image-url: http://localhost:8090/productimgs/

# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용
# open ssl 에서 생성 가능 찾아보자~
jwt:
  secret: dW5pLXJlYWN0LW5naW54LXNwcmluZy1ib290LWp3dC1vcmFjbGUtZG9ja2VyLWVjMi1yZWFjdC1uZ25peC1zcHJpbmctYm9vdC1qd3Qtb3JhY2xlLWRvY2tlci1lYzIK


mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/*.xml
  # alias Setting
#  type-aliases-package: com.uni.reactpro
  type-aliases-package: com.ssssong.choonsik
  configuration:
    #카멜케이스 on ?
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
